### ISSUE TITLE
Antivirus blocks a creating Win PE

### ISSUE THREAD

**Issue by UKI-COMPUTERS** [ChrisRfr/Win10XPE#10]
Hi! If you can see antivirus blocks creating Win PE beacuse is Avast Antivirus detected as a IDP.Helu.Autolt10. Please help me how to reslove this

**Comment by ied206** [comment]
## Summary

AutoIt itself is not a virus, so you can ignore and whitelist the Win PE directory.

## Details

AutoIt is a useful toolkit to automate many things, think of it as a cooking knife.
Unfortunately, some crackers exploited AutoIt for their crime, that's why antiviruses tend to treat AutoIt itself like malware.
The cooking knife itself can be used in a crime, but that is a problem of the malicious person, not a problem of the knife.

You can also see a message of ChrisRfr on README.md:

> Note AV: By its nature, Win10XPE uses programs or applications which uses functions at the core of windows.
Some AntiVirus mark them as positive. These are false alarms.
An example with NirSoft's ProduKey to Recover lost Windows product key, 12 engines detected this file as Unsafe or Hacktool, that's not true.
You can read this blog written by the same author as ProduKey: [Antivirus companies cause a big headache to small developers.](https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/)
Blog written in 2009, the situation did not get any better.
It shouldn't be like that and it's really frustrating. The work of AV companies should be better.
They should be reprimanded for this, we are their customers.
I can only advise you to put an exclusion on the Win10XPE folder.

**Comment by UKI-COMPUTERS** [comment]
I'am added exception on avast and all super working. Thank you very much. 🙂
