### ISSUE TITLE
Adding Optional Packages

### ISSUE THREAD

**Issue by TravisArmstrong** [ChrisRfr/Win10XPE#3]
A few questions for you:

Is there a method to add WinPE additional packages via the GUI?
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-add-packages--optional-components-reference

I have a program that requires the following not included in the default build:
NetFX
PowerShell
SecureBootCmdlets

Attempting to add these manually via dism after building as normal fails. Perhaps due to the already existing older NetFXv3 integration?

Any help is appreciated.

**Comment by ChrisRfr** [comment]
The project does not use the WinPE Optional Components, [the Windows Assessment and Deployment Kit](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install) (ADK) is not required.
But all Components, and much more, are available in Win10XPE 

In "Build Core" there is an option to add "Microsoft .NETFx4"

In addition, If you need .NET Framework 2.0-3.5 there is a plugin "Utilities\NETFx3 Add-Feature" to Enables (or Disables) .NET Framework 2.0-3.5 Support. It must be done beforehand before building 

There are 2 possibilities (plugins) for PowerShell
1) "Apps\Components\PowerShell Core" version 7.0.3 from https://github.com/PowerShell/PowerShell
2) Download "XPE OPTIONAL ADD-ON BASE PACKAGE" from "Utilities\Mega Optional Application Download"
    You will then find a new plugin "Apps\Components\MS PowerShell" to add Windows PowerShell 5.1 As well as many other Application plugins</br></br>


 
Otherwise, for information, here is the list of WinRE's included features:
```
WinPE-EnhancedStorage                           
Microsoft-Windows-WinPE-ATBroker-Package        
Microsoft-Windows-WinPE-ATBroker-Package        
Microsoft-Windows-WinPE-Speech-TTS-Package      
Microsoft-Windows-WinPE-Speech-TTS-Package      
Microsoft-Windows-WinPE-Speech-TTS-fr-FR-Package
WinPE-FMAPI-Package                             
WinPE-SRT                                       
WinPE-HTA                                       
WinPE-WDS-Tools                                 
WinPE-Scripting                                 
WinPE-Rejuv                                     
Microsoft-Windows-WinPE-AudioCore-Package       
Microsoft-Windows-WinPE-AudioCore-Package       
WinPE-WMI                                       
WinPE-StorageWMI                                
WinPE-SecureStartup                             
WinPE-TPM                                       
WinPE-WiFi                                      
Microsoft-Windows-WinPE-SRH-Package             
Microsoft-Windows-WinPE-SRH-Package             
Microsoft-Windows-WinPE-AudioDrivers-Package    
Microsoft-Windows-WinPE-AudioDrivers-Package    
Microsoft-Windows-WinPE-Narrator-Package        
Microsoft-Windows-WinPE-Narrator-Package 
```

**Comment by TravisArmstrong** [comment]
Thank you for the information.

You mention that **all** components are available but unfortunately the list you provide isn't comprehensive when compared to Microsoft's list of available packages, and doesn't cover SecureBootCmdlets or other potential items.

Is there a method to add these without the ADK since you've mentioned it isn't required?

**Comment by ChrisRfr** [comment]
Win10XPE doesn't use the WinPE optional components from ADK.
It's not based on it, so it's hard to tell you one by one all those that are included.

But many of them are included by default in the base (ex: Scripting, WMI, Network and WiFi, Windows Recovery Environment,...)
And others, as additional plugins (.NET Framework, PowerShell, PPPoE Network,...)
SecureBootCmdlets is included in the 2 powershell plugins.

I don't think I'm wrong in saying that it is **much more complete** than a WinPE built by adding ADK components.
With explorer, network with  browser, disk management,... and many application plugins available 
The best is to build and discover by yourself
