### ISSUE TITLE
Preserving Registry Keys on Win10XPE or WinPE ( Technichal )

### ISSUE THREAD

**Issue by Bit00009** [ChrisRfr/Win10XPE#5]
Hi there @ChrisRfr 
I'm searching for a special thing about Win10XPE and since you are a very skilled person which knows the structure of windows I will be thankful if you can give me any hint or guide.

**I'm using Win10XPE from disk mode instead of RamDisk** so it just boot as a regular windows, has drivers installed and all changes to files are fine but only registery...
I know WinPE loads a clone of registery hives and there's a function known as `RegFlushKey` to write this changes back to the hives but it only works on windows not winpe...

So I'm just wondering if there will be any option in winpe structure or someplace that you know about it ?
I also tried safe shutdown of **wpeutil** but no chance : )

**I already using my solution to this and it works! but it needs lots of development every time :** 
- I made a kernel-driver which catches processes creations/termination events.
- I made a user-mode application which gets notified from driver when a new process starts and this application loads disk hives to registery as temp keys.
- I made a small detour engine which hooks registery functions and API and alternates them to a pre-pass function, whenever the application attempts to change registery detoured function catch it and apply the change to both online and offline hives, online hives to keep OS working and offline hives to preserving changes.
- I compiled detour engine in a x64 and x86 shellcode and used user-mode application to detect new created process architecture and inject the proper shellcode to them.
- Before WinPE shutdown I unload offline hives and save them back to the disk.

Here's more detail on [here.](https://docs.microsoft.com/en-us/answers/questions/174163/how-to-active-or-save-registery-in-winpe-with-non.html)

it would be a great feature for Win10XPE as well if we figure this out...

Regards,
Ultran

**Comment by ChrisRfr** [comment]
It looks like a nice development, very interesting.
I don't know much about kernel-driver or your small detour engine. Uutside of my knowledge
I've just tried, a long time ago, Win10XPE flat mode (instead of RamDisk) but I don't really use it.
Did you use this guide:
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-install-on-a-hard-drive--flat-boot-or-non-ram

It seems a good idea to unload the offline hives and save them to disk when shutting down.
I'm afraid I can't help, I don't know more. You seem to know better. 
Let me know if I can help, your approach is interesting
